version: "3"
services:
    nginx:
        image: nginx:inc
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        ports:
            - 443:443
        networks:
            - my-network
#        container_name: nginx
#        restart: always

#    wordpress_php:
#        build: ./wordpress
#        ports:
#            - 9000:80
#        networks:
#            - my-network

networks:
    my-network:
#
#        volumes:
#            - ./src:/usr/share/nginx/html

