version: "3.5"
services:

  nginx:
    container_name: nginx
    depends_on:
      - wordpress-php
    image: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 443:443
    hostname: www
    networks:
      - my-network
    volumes:
      - /home/dait-atm/data/wordpress:/var/www/wordpress
    #domainname: dait-atm.42.fr
    #extra_hosts:
    #  - "dait-atm.42.fr:0.0.0.0"

  wordpress-php:
    container_name: wordpress-php
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - wordpress.env
    ports:
      - 9000:9000
    hostname: wordpress
    networks:
      - my-network
    volumes:
      - /home/dait-atm/data/wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    env_file:
      - mariadb.env
    ports:
      - 3306:3306
    networks:
      - my-network
    volumes:
      - /home/dait-atm/data/mariadb:/var/lib/mysql

networks:
  my-network:
    driver: bridge
