version: "3.5"
services:

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    hostname: www
    networks:
      - my-network
    volumes:
      - wordpress_volume:/var/www/my_server/
    #domainname: dait-atm.42.fr
    #extra_hosts:
    #  - "dait-atm.42.fr:0.0.0.0"

#  wordpress_php:
#    container_name: wordpress
#    build:
#      context: ./requirements/wordpress
#      dockerfile: Dockerfile
#    env_file:
#      - wordpress.env
#    environment:
#      WP_ADMIN:             "{WP_ADMIN}"
#      WP_ADMIN_PASSWORD:    "{WP_ADMIN_PASSWORD}"
#      WP_USER:              "{WP_USER}"
#      WP_USER_PASSWORD:     "{WP_USER_PASSWORD}"
#      MYSQL_DB_NAME:        "{MYSQL_DB_NAME}"
#      MYSQL_USER:           "{MYSQL_USER}"
#      MYSQL_USER_PASSWORD:  "{MYSQL_USER_PASSWORD}"
#      MYSQL_ADMIN:          "{MYSQL_ADMIN}"
#      MYSQL_ADMIN_PASSWORD: "{MYSQL_ADMIN_PASSWORD}"
#    ports:
#      - 9000:9000
#    hostname: wordpress
#    networks:
#      - my-network
#    depends_on:
#      - nginx
#    volumes:
#      - ~/data/wordpress:/var/www/wordpress

#  mariadb:
#    container_name: mariadb
#    image: mariadb
#    build:
#      context: requirements/mariadb
#      dockerfile: Dockerfile
#    ports:
#      - 3306:3306
#    networks:
#      - my-network
#    env_file:
#      - mariadb.env
#    volumes:
#      - /home/dait-atm/data/mariadb:/var/lib/mysql

networks:
  my-network:
    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/user42/data/wordpress'
