version: "3.3"
services:
    web:
        build: ./nginx/
        ports:
            - 80:80
            - 443:443
#        networks:
#            - my-network

#    wordpress_php:
#        build: ./wordpress
#        ports:
#            - 9000:80
#        networks:
#            - my-network

#networks:
#    my-network:
#
#        volumes:
#            - ./src:/usr/share/nginx/html

