version: "3.5"
services:
#    nginx:
#        container_name: nginx
#        image: nginx
#        build:
#            context: requirements/nginx
#            dockerfile: Dockerfile
#        ports:
#            - 443:443
#        networks:
#            - my-network
#        restart: always

#    wordpress_php:
#        container_name: wordpress
#        build: ./wordpress
#        ports:
#            - 9000:80
#        networks:
#            - my-network

    mariadb:
        container_name: mariadb
        image: mariadb
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        ports:
            - 3306:3306
        networks:
            - my-network
        env_file:
            - mariadb.env

networks:
    my-network:
        name: Inception
#
#        volumes:
#            - ./src:/usr/share/nginx/html

