apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql-app
        image: dait-atm/mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql-port-depl
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql/
        env:
        - name: MYSQL_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_db_name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_user
        - name: MYSQL_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_user_password
        - name: MYSQL_ADMIN
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_admin
        - name: MYSQL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_admin_password
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  selector:
    app: mysql-app
  type: ClusterIP
  ports:
  - port: 3306
    name: http-port-service
    protocol: TCP
    targetPort: mysql-port-depl
