apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql_db_name: d29yZHByZXNz
  mysql_user: ZGFpdC1hdG0=
  mysql_user_password: cGFzc3dvcmQ=
  mysql_admin: YWRtaW4=
  mysql_admin_password: dG9vcg==
