# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv-volume
#   labels:
#     type: local
# spec:
#   storageClassName: standard
#   capacity:
#     storage: 100Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"
#   persistentVolumeReclaimPolicy: Retain

# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
