apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-app
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      containers:
      - name: ftps-app
        image: dait-atm/ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps-dp-21
        - containerPort: 20
          name: ftps-dp-20
        - containerPort: 30000
          name: ftps-dp-30000
        - containerPort: 30001
          name: ftps-dp-30001
        - containerPort: 30002
          name: ftps-dp-30002
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /home/admin
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  selector:
    app: ftps-app
  type: LoadBalancer
  loadBalancerIP: 192.168.49.42
  ports:
  - port: 21
    name: ftps-sp-21
    protocol: TCP
    targetPort: ftps-dp-21
  - port: 20
    name: ftps-sp-20
    protocol: TCP
    targetPort: ftps-dp-20
  - port: 30000
    name: ftps-sp-30000
    protocol: TCP
    targetPort: ftps-dp-30000
  - port: 30001
    name: ftps-sp-30001
    protocol: TCP
    targetPort: ftps-dp-30001
  - port: 30002
    name: ftps-sp-30002
    protocol: TCP
    targetPort: ftps-dp-30002
